# .github/workflows/caller-workflow.yml
name: Caller Workflow

on: [push]

jobs:
  call-reusable-workflow:
    uses: swesadiqul/second-workflow/.github/workflows/reusable-workflow.yml@main
    with:
      python-version: "3.10"

