name: Cronjob Workflow

on:
    schedule:
        - cron: '*/5 * * * *' # Run the cron job on every 5 minutes

jobs:
  cronjob-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
         echo "Hello, Python CI"
         echo "I'm running a second workflow"
