name: Matrix Workflow

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # একটি জব ব্যর্থ হলেও অন্যগুলো চলবে
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]  # সমর্থিত Python ভার্সন
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash  # Ubuntu এবং macOS-এ bash ব্যবহার করবে
        if: runner.os != 'Windows'

      - name: Install dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
        shell: cmd  # Windows-এর জন্য cmd ব্যবহার করবে
        if: runner.os == 'Windows'

      - name: Run tests
        run: |
          pytest




