name: Predefine Workflow

on:
    workflow_dispatch:

jobs:
    predefine_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Python Version
              run: python --version