name: Predefine Workflow

on:
    workflow_dispatch:

jobs:
    predefine_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Python Version
              run: python --version

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Updated Python Version
              run: python --version