# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call: # এটা অত্যাবশ্যক, caller workflow-কে enable করে

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Log Message
        run: echo "This is a reusable workflow!"






