name: Value Pass Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Unnamed'

jobs:
  First-Job:
    runs-on: ubuntu-latest

    outputs: # Define outputs for the job
      greeting: ${{ steps.generate-greetings-messages.outputs.greeting }}

    steps:
      - name: Generate Greeting Message
        id: generate-greetings-messages
        run: |
          echo "greeting=Hello, ${{ github.event.inputs.name }}!" >> $GITHUB_ENV

      - name: Set Output from Environment File
        id: set-output
        run: |
          echo "greeting=${{ steps.generate-greetings-messages.outputs.greeting }}" >> $GITHUB_ENV

  Second-Job:
    needs: First-Job
    runs-on: ubuntu-latest

    steps:
      - name: Use Greeting Message
        run: |
          echo "Greeting Received: ${{ needs.First-Job.outputs.greeting }}"
